---
- name: Configure service file {{ tomcat_service_name }}.service for Amazon Linux
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/{{ tomcat_service_name }}.service
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'

- name: Configure Environment variables for tomcat
  template:
    src: setenv.sh.j2
    dest: "{{ tomcat_direcory }}/bin/setenv.sh"
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'

- name: Setup logging.properties
  template:
    src: "logging.properties-{{ '.'.join(tomcat_version.split('.')[:2]) }}.j2"
    dest: "{{ tomcat_direcory }}/conf/logging.properties"

- name: Enable tomcat service on startup
  systemd:
    name: "{{ tomcat_service_name }}"
    enabled: true
    daemon-reload: true
    state: restarted

- name: Setup server.xml
  template:
    src: "tomcat-server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"
    dest: "{{ tomcat_direcory }}/conf/server.xml"
  notify: restart tomcat
