---
# tasks file for tomcat-ansible-role

- name: Configure service file {{ tomcat_service_name }}.service for ubuntu 16 , rhel 7 and amazon linux
  template:
    src: tomcat.service.j2
    dest: /usr/lib/systemd/system/{{ tomcat_service_name }}.service
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "16") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "7")

- name: Configure service file {{ tomcat_service_name }} for ubuntu 14 and rhel 6 
  template:
    src: tomcat-script.j2
    dest: /etc/init.d/{{ tomcat_service_name }}
    owner: "{{ tomcat_user }}"
    group: "{{ tomcat_group }}"
    mode: '0755'
  when: (ansible_distribution == "Ubuntu" and ansible_distribution_major_version == "14") or
        (ansible_distribution == "RedHat" and ansible_distribution_major_version == "6")

- name: Enable tomcat service on startup
  service:
    name: "{{ tomcat_service_name}}"
    enabled: yes
    state: restarted

- name: Setup server.xml
  template:
    src: "tomcat-server-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/server.xml"
  notify: restart tomcat

- name: Setup tomcat-users.xml
  template:
    src: "tomcat-users-{{ '.'.join(tomcat_version.split('.')[:2]) }}.xml.j2"
    dest: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}/conf/tomcat-users.xml"
  notify: restart tomcat