---
# tasks file for tomcat-ansible-role

- name: check Java version
  shell: java -version 2>&1 | grep version | awk '{print $3}' | awk -F"_" '{print $1}'| sed 's/"//g'
  register: java_version

- name: Print message if correct version of java is not installed
  fail:
    msg: "java version is not compatible with {{ tomcat_version }}"
  when: (java_version.stdout < "1.6" and tomcat_version.split('.')[0] == "7") or
         (java_version.stdout < "1.7" and tomcat_version.split('.')[0] == "8")

- name: Checking apache-tomcat-{{ tomcat_version }} directory at install path
  stat:
    path: "{{ tomcat_install_path }}/apache-tomcat-{{ tomcat_version }}"
  register: is_available

- name: Installing tomcat
  include: install.yml
  when: is_available.stat.exists == False
  
- name: Configure tomcat in {{ ansible_distribution }}
  include: "{{ ansible_distribution }}.yml"




