---
dependency:
  name: galaxy
driver:
  name: docker
lint: |   
        yamllint .
platforms:
  - name: ubuntu-16.04
    image: solita/ubuntu-systemd
    image_version: latest
    privileged: true
    command: '/sbin/init'
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: ubuntu-14.04
    image: ubuntu:14.04
    privileged: true
  - name: centos-7
    image: solita/centos-systemd
    image_version: latest
    privileged: true
    security_opts:
      - seccomp=unconfined
    tmpfs:
      - /run
      - /tmp
      - /run/lock
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
provisioner:
  name: ansible
verifier:
  name: testinfra
scenario:
  name: default
  test_sequence:        # molecule test
   - lint
   - cleanup
   - destroy
   - dependency
   - syntax
   - create
   - prepare
   - converge
   - side_effect
   - verify
   - cleanup
   - destroy
